
; PIC16F877A Configuration Bit Settings

; Assembly source line config statements

#include "p16f877a.inc"

; CONFIG
; __config 0x3F32
 __CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF

    
	ORG	0
	GOTO	INICIO
	ORG	0X0020
INICIO
	CALL	LCD_INIT
	MOVLW	.0
	CALL	LCD_LINEA1
	MOVLW	'A'
	CALL	LCD_CARACTER
	MOVLW	'N'
	CALL	LCD_CARACTER
	MOVLW	'G'
	CALL	LCD_CARACTER
	MOVLW	'E'
	CALL	LCD_CARACTER
	MOVLW	'L'
	CALL	LCD_CARACTER
	MOVLW	'O'
	CALL	LCD_CARACTER
	MOVLW	' '
	CALL	LCD_CARACTER
	MOVLW	'S'
	CALL	LCD_CARACTER
	MOVLW	'A'
	CALL	LCD_CARACTER
	MOVLW	'N'
	CALL	LCD_CARACTER
	MOVLW	'C'
	CALL	LCD_CARACTER
	MOVLW	'H'
	CALL	LCD_CARACTER
	MOVLW	'E'
	CALL	LCD_CARACTER
	MOVLW	'Z'
	CALL	LCD_CARACTER
	MOVLW	.0
	CALL	LCD_LINEA2
	MOVLW	'L'
	CALL	LCD_CARACTER
	MOVLW	'O'
	CALL	LCD_CARACTER
	MOVLW	'J'
	CALL	LCD_CARACTER
	MOVLW	'A'
	CALL	LCD_CARACTER
	MOVLW	' '
	CALL	LCD_CARACTER
	MOVLW	'I'
	CALL	LCD_CARACTER
	MOVLW	'D'
	CALL	LCD_CARACTER
	MOVLW	':'
	CALL	LCD_CARACTER
	MOVLW	'2'
	CALL	LCD_CARACTER
	MOVLW	'5'
	CALL	LCD_CARACTER
	MOVLW	'7'
	CALL	LCD_CARACTER
	MOVLW	'7'
	CALL	LCD_CARACTER
	MOVLW	'2'
	CALL	LCD_CARACTER
	MOVLW	'2'
	CALL	LCD_CARACTER
	
START
	GOTO	START
#INCLUDE <Libreria.inc>	
	END